name: Update Proxy IPs with First Record Check

on:
  workflow_dispatch: # 允许手动触发工作流
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 运行

jobs:
  update_ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download raw data
      run: |
        curl -s "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt" > raw_data.txt # 替换为你的 raw 文件 URL

    - name: Extract first 100 records
      run: |
        head -n 100 raw_data.txt > first_100_records.txt

    - name: Extract IPs and ports from first 100
      run: |
        cat first_100_records.txt | awk -F',' '{print $1":"$2}' > new_proxyip.txt

    - name: Check if first record changed
      id: check_change
      run: |
        FIRST_RECORD_NEW=$(head -n 1 new_proxyip.txt)
        FIRST_RECORD_OLD=$(head -n 1 proxyip.txt)
        if [ "$FIRST_RECORD_NEW" != "$FIRST_RECORD_OLD" ]; then
          echo "::set-output name=changed::true"
        else
          echo "::set-output name=changed::false"
        fi
        echo "new: $FIRST_RECORD_NEW"
        echo "old: $FIRST_RECORD_OLD"

    - name: Clear proxyip.txt for next update
      if: steps.check_change.outputs.changed == 'true'
      run: |
        echo "" > proxyip.txt

    - name: Update proxyip.txt if changed
      if: steps.check_change.outputs.changed == 'true'
      run: |
        mv new_proxyip.txt proxyip.txt

    - name: Commit and push changes
      if: steps.check_change.outputs.changed == 'true'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add proxyip.txt
        git commit -m "Update proxyip.txt if first record changed"
        git push origin HEAD:main
