name: Extract Proxy IPs and Commit

on:
  workflow_dispatch: # 允许手动触发工作流

jobs:
  extract_ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download raw data
      run: |
        curl -s "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt" > raw_data.txt # 替换为你的 raw 文件 URL

    - name: Set file permissions
      run: chmod +rw proxyip.txt
    
    - name: Convert file encoding
      run: iconv -f UTF-8 -t UTF-8 proxyip.txt -o proxyip.txt
    
    - name: Extract IPs and ports
      run: |
        cat raw_data.txt | awk -F',' '{print $1":"$2}' > proxyip.txt

    - name: Commit changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add proxyip.txt
        git commit -m "Update proxyip.txt with generated data" || echo "No changes to commit"

    - name: Push changes to main
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
