name: Update Proxy PL_IPs 

on:
  workflow_dispatch: # 允许手动触发工作流
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 运行

jobs:
  update_ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download raw data
      run: |
        curl -s "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt" > raw_data.txt # 替换为你的 raw 文件 URL

    - name: Extract PL IPs and ports
      run: |
        awk -F',' '$4 ~ /PL/ {print $1":"$2}' raw_data.txt > pl_ips.txt

    - name: Convert to JSON
      run: |
        jq -R -s -c '[split("\n") | map(select(length > 0))]' pl_ips.txt > proxyip.json

    - name: Clear proxyip.json
      run: |
        echo "[]" > proxyip.json

    - name: Update proxyip.json
      run: |
        cp pl_ips.txt temp.txt;
        jq -R -s -c '[split("\n") | map(select(length > 0))]' temp.txt > proxyip.json;
        rm temp.txt

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add proxyip.json
        git commit -m "Update proxyip.json with PL data"
        git push origin HEAD:main
