name: Update Proxy IPs as JSON with PL Filter

on:
  workflow_dispatch: # 允许手动触发工作流
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 运行

jobs:
  update_ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download raw data
      run: |
        curl -s "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt" > raw_data.txt # 替换为你的 raw 文件 URL

    - name: Extract PL IPs and ports
      run: |
        awk -F',' '$4 ~ /PL/ {print $1":"$2}' raw_data.txt > pl_ips.txt

    - name: Convert to JSON
      run: |
        jq -R -s -c '[split("\n") | map(select(length > 0))]' pl_ips.txt > proxyip.json

    - name: Check if first record changed
      id: check_change
      run: |
        FIRST_RECORD_NEW=$(jq -r '.[0]' proxyip.json)
        FIRST_RECORD_OLD=$(jq -r '.[0]' proxyip.json) #这里使用json文件自身，用于第一次比较，后续的比较需要使用旧的json文件
        if [ "$FIRST_RECORD_NEW" != "$FIRST_RECORD_OLD" ]; then
          echo "::set-output name=changed::true"
        else
          echo "::set-output name=changed::false"
        fi
        echo "new: $FIRST_RECORD_NEW"
        echo "old: $FIRST_RECORD_OLD"

    - name: Clear proxyip.json for next update
      if: steps.check_change.outputs.changed == 'true'
      run: |
        echo "[]" > proxyip.json

    - name: Commit and push changes
      if: steps.check_change.outputs.changed == 'true'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add proxyip.json
        git commit -m "Update proxyip.json if first record changed"
        git push origin HEAD:main
