name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install requests pyaes

    - name: Clear ss12.txt
      run: |
        echo "" > ss12.txt

    - name: Run the script
      run: |
        python getvpn.py | grep -v '^$' >> ss12.txt

    - name: 提交更改
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add ss12.txt
        git commit -m "Update ss12.txt with generated data" || echo "No changes to commit"

    - name: Push changes to main
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
